channels:
  - defaults
dependencies:
  - python=3.10.4
  - ipykernel
  - pip
  - pip:
    - pandas==1.4.2
    - numpy==1.22.3
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - tensorflow==2.8.0
    - tqdm==4.64.0